apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops
  namespace: prop-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: development
  namespace: prop-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre
  namespace: prop-development
